### ISSUE TITLE
HTTPS - mixed content security errors

### ISSUE THREAD

**Issue by domingobishop** [nationalarchives/tna-child-home#14]
Because of mixed content security errors when the homepage is served over https we need to make sure that any linked assets in our themes are loaded over https - I've updated the newsletter icon to load over https but have noticed that the footer social media icons in the new homepage all load over http and so cause mixed content errors when the page is loaded over https

**Comment by grange85** [comment]
@domingobishop where did we stand on this - I have a feeling this was ultimately unrelated to the theme and more to do with actually having our content available over https and then linking to that - I think we should close and then look closer at mixed content issues as a separate piece of work. Thoughts??
