### ISSUE TITLE
Give marketing training on how to upload images for the hero banner and insert the URL (not the image code)

### ISSUE THREAD

**Issue by sdwilkes** [nationalarchives/tna-child-home#50]
Marketing have reported that uploading an image vie 'Add Media' doesn't work as expected...

**Comment by domingobishop** [comment]
Could we have a little more information why it's not working as expected? It appears to be working fine on my end.

**Comment by domingobishop** [comment]
Discussed with Simon and it appears marketing needs training so they are inserting the image URL and not the image code.
