### ISSUE TITLE
External links in banner and cards should open in new window

### ISSUE THREAD

**Issue by sdwilkes** [nationalarchives/tna-child-home#53]
External links added to banners and card currently open in the same window as internal links. Only TNA links should open in same window.

**Comment by domingobishop** [comment]
@sdwilkes, maybe check with Carianne. I now recall a discussion that the only time we'd link externally is to Eventbrite. Everything else, for context and orientation reasons, should link internally. For special cases, for example a partnering site we want to feature, we would create a news or blog item about the feature, and link to this from the homepage.
